"""add_remaining_models_with_varchar_lengths

Revision ID: 13da8fe234e3
Revises: add_categoria_column
Create Date: 2025-10-14 18:49:01.339932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13da8fe234e3'
down_revision = 'add_categoria_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('challenge_type', sa.Enum('SIMPLE', 'PROGRESS', 'CHECKLIST', name='challengetype'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='challengestatus'), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('checklist_items', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('daily_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reto_id', sa.Integer(), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reto_id'], ['reto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_challenges_challenge_date'), 'daily_challenges', ['challenge_date'], unique=False)
    op.create_index(op.f('ix_daily_challenges_id'), 'daily_challenges', ['id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habit_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='habittype'), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_id'), 'habits', ['id'], unique=False)
    op.create_table('progress_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_records_id'), 'progress_records', ['id'], unique=False)
    op.alter_column('criterio', 'id_reto',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('criterio', 'desc_criterio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('criterio', 'tiempo_est',
               existing_type=mysql.TIME(),
               nullable=True)
    op.create_index(op.f('ix_criterio_id'), 'criterio', ['id'], unique=False)
    op.create_foreign_key(None, 'criterio', 'reto', ['id_reto'], ['id'])
    op.add_column('criterio_reto', sa.Column('id_reto', sa.Integer(), nullable=False))
    op.add_column('criterio_reto', sa.Column('fecha_prim_ra', sa.Date(), nullable=True))
    op.alter_column('criterio_reto', 'id_reto_usuario',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('criterio_reto', 'id_criterio',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('criterio_reto', 'completado',
               existing_type=sa.BINARY(length=50),
               nullable=True,
               existing_server_default=sa.text("'\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0'"))
    op.alter_column('criterio_reto', 'fecha_ul_modif',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_criterio_reto_id'), 'criterio_reto', ['id'], unique=False)
    op.create_foreign_key(None, 'criterio_reto', 'reto', ['id_reto'], ['id'])
    op.create_foreign_key(None, 'criterio_reto', 'reto_usuario', ['id_reto_usuario'], ['id'])
    op.create_foreign_key(None, 'criterio_reto', 'criterio', ['id_criterio'], ['id'])
    op.drop_column('criterio_reto', 'fecha_prim_racha')
    op.alter_column('daily_challenge_templates', 'categoria',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('SOCIAL', 'FISICA', 'INTELECTUAL', name='retocategoria'),
               existing_nullable=True)
    op.add_column('logros', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_logros_id'), 'logros', ['id'], unique=False)
    op.create_foreign_key(None, 'logros', 'reto_usuario', ['id_reto_usuario'], ['id'])
    op.create_foreign_key(None, 'logros', 'usuario', ['id_usuario'], ['id'])
    op.alter_column('reto', 'nombre_reto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('reto', 'descripcion_reto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('reto', 'tipo',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reto_id'), 'reto', ['id'], unique=False)
    op.create_index(op.f('ix_reto_usuario_id'), 'reto_usuario', ['id'], unique=False)
    op.create_foreign_key(None, 'reto_usuario', 'usuario', ['id_usuario'], ['id'])
    op.create_foreign_key(None, 'reto_usuario', 'reto', ['id_reto'], ['id'])
    op.alter_column('usuario', 'img_foto_usuario',
               existing_type=sa.BLOB(),
               type_=sa.BINARY(),
               existing_nullable=True)
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.alter_column('usuario', 'img_foto_usuario',
               existing_type=sa.BINARY(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.drop_constraint(None, 'reto_usuario', type_='foreignkey')
    op.drop_constraint(None, 'reto_usuario', type_='foreignkey')
    op.drop_index(op.f('ix_reto_usuario_id'), table_name='reto_usuario')
    op.drop_index(op.f('ix_reto_id'), table_name='reto')
    op.alter_column('reto', 'tipo',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('reto', 'descripcion_reto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('reto', 'nombre_reto',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_constraint(None, 'logros', type_='foreignkey')
    op.drop_constraint(None, 'logros', type_='foreignkey')
    op.drop_index(op.f('ix_logros_id'), table_name='logros')
    op.drop_column('logros', 'id_usuario')
    op.alter_column('daily_challenge_templates', 'categoria',
               existing_type=sa.Enum('SOCIAL', 'FISICA', 'INTELECTUAL', name='retocategoria'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('criterio_reto', sa.Column('fecha_prim_racha', sa.DATE(), nullable=False))
    op.drop_constraint(None, 'criterio_reto', type_='foreignkey')
    op.drop_constraint(None, 'criterio_reto', type_='foreignkey')
    op.drop_constraint(None, 'criterio_reto', type_='foreignkey')
    op.drop_index(op.f('ix_criterio_reto_id'), table_name='criterio_reto')
    op.alter_column('criterio_reto', 'fecha_ul_modif',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('criterio_reto', 'completado',
               existing_type=sa.BINARY(length=50),
               nullable=False,
               existing_server_default=sa.text("'\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0'"))
    op.alter_column('criterio_reto', 'id_criterio',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('criterio_reto', 'id_reto_usuario',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('criterio_reto', 'fecha_prim_ra')
    op.drop_column('criterio_reto', 'id_reto')
    op.drop_constraint(None, 'criterio', type_='foreignkey')
    op.drop_index(op.f('ix_criterio_id'), table_name='criterio')
    op.alter_column('criterio', 'tiempo_est',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('criterio', 'desc_criterio',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('criterio', 'id_reto',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_progress_records_id'), table_name='progress_records')
    op.drop_table('progress_records')
    op.drop_index(op.f('ix_habits_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_daily_challenges_id'), table_name='daily_challenges')
    op.drop_index(op.f('ix_daily_challenges_challenge_date'), table_name='daily_challenges')
    op.drop_table('daily_challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###