"""change reto description and name to text

Revision ID: 20251016_change_text
Revises: 13da8fe234e3
Create Date: 2025-10-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20251016_change_text'
down_revision = '13da8fe234e3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reto', 'nombre_reto',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('reto', 'descripcion_reto',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reto', 'descripcion_reto',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('reto', 'nombre_reto',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###