"""set_current_value_not_null

Revision ID: 5c0ea00fc4d9
Revises: 13da8fe234e3
Create Date: 2025-10-15 14:56:37.199758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c0ea00fc4d9'
down_revision = '13da8fe234e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'current_value',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenges', 'current_value',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###